services:
  - type: web
    name: llm-quiz-api
    env: python
    buildCommand: cd llm-quiz-project && ./build.sh
    startCommand: cd llm-quiz-project && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.12
